# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe424776ff6a173340b2aed970fe13d598fed5275229d4704bc2cd6c341d85c2b07ced6af5a0ebdf5499f7da7b76a4e90d016aa48aafd2dc5af44752971a241

test:
  secret_key_base: 4163e24a0c7281d98ca5ff95a5eddb78a8c13a36e4ad20ca34ebf6acfaaa34e8fa3bc2db4afc45e873fe5903bddf131cbae6a4470438117b0c55ef4d046dc909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
